//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.UserAndPaymentServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserAndPaymentServiceReference.IUserAndPaymentService")]
    public interface IUserAndPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/addUser", ReplyAction="http://tempuri.org/IUserAndPaymentService/addUserResponse")]
        void addUser(string email, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/addUser", ReplyAction="http://tempuri.org/IUserAndPaymentService/addUserResponse")]
        System.Threading.Tasks.Task addUserAsync(string email, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/isConnectionOK", ReplyAction="http://tempuri.org/IUserAndPaymentService/isConnectionOKResponse")]
        bool isConnectionOK(string email, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/isConnectionOK", ReplyAction="http://tempuri.org/IUserAndPaymentService/isConnectionOKResponse")]
        System.Threading.Tasks.Task<bool> isConnectionOKAsync(string email, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/getListUsers", ReplyAction="http://tempuri.org/IUserAndPaymentService/getListUsersResponse")]
        string getListUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/getListUsers", ReplyAction="http://tempuri.org/IUserAndPaymentService/getListUsersResponse")]
        System.Threading.Tasks.Task<string> getListUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/getMyBills", ReplyAction="http://tempuri.org/IUserAndPaymentService/getMyBillsResponse")]
        string getMyBills(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/getMyBills", ReplyAction="http://tempuri.org/IUserAndPaymentService/getMyBillsResponse")]
        System.Threading.Tasks.Task<string> getMyBillsAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/addPayment", ReplyAction="http://tempuri.org/IUserAndPaymentService/addPaymentResponse")]
        bool addPayment(long id, string email, int cb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/addPayment", ReplyAction="http://tempuri.org/IUserAndPaymentService/addPaymentResponse")]
        System.Threading.Tasks.Task<bool> addPaymentAsync(long id, string email, int cb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/getListPayments", ReplyAction="http://tempuri.org/IUserAndPaymentService/getListPaymentsResponse")]
        string getListPayments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAndPaymentService/getListPayments", ReplyAction="http://tempuri.org/IUserAndPaymentService/getListPaymentsResponse")]
        System.Threading.Tasks.Task<string> getListPaymentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAndPaymentServiceChannel : UnitTestProject.UserAndPaymentServiceReference.IUserAndPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAndPaymentServiceClient : System.ServiceModel.ClientBase<UnitTestProject.UserAndPaymentServiceReference.IUserAndPaymentService>, UnitTestProject.UserAndPaymentServiceReference.IUserAndPaymentService {
        
        public UserAndPaymentServiceClient() {
        }
        
        public UserAndPaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAndPaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAndPaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAndPaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addUser(string email, string mdp) {
            base.Channel.addUser(email, mdp);
        }
        
        public System.Threading.Tasks.Task addUserAsync(string email, string mdp) {
            return base.Channel.addUserAsync(email, mdp);
        }
        
        public bool isConnectionOK(string email, string mdp) {
            return base.Channel.isConnectionOK(email, mdp);
        }
        
        public System.Threading.Tasks.Task<bool> isConnectionOKAsync(string email, string mdp) {
            return base.Channel.isConnectionOKAsync(email, mdp);
        }
        
        public string getListUsers() {
            return base.Channel.getListUsers();
        }
        
        public System.Threading.Tasks.Task<string> getListUsersAsync() {
            return base.Channel.getListUsersAsync();
        }
        
        public string getMyBills(string email) {
            return base.Channel.getMyBills(email);
        }
        
        public System.Threading.Tasks.Task<string> getMyBillsAsync(string email) {
            return base.Channel.getMyBillsAsync(email);
        }
        
        public bool addPayment(long id, string email, int cb) {
            return base.Channel.addPayment(id, email, cb);
        }
        
        public System.Threading.Tasks.Task<bool> addPaymentAsync(long id, string email, int cb) {
            return base.Channel.addPaymentAsync(id, email, cb);
        }
        
        public string getListPayments() {
            return base.Channel.getListPayments();
        }
        
        public System.Threading.Tasks.Task<string> getListPaymentsAsync() {
            return base.Channel.getListPaymentsAsync();
        }
    }
}
