//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long IdCommande { get; set; }
        public string User { get; set; }

        public string ToString()
        {
            return "Id commande : " + IdCommande + " User : " + User;
        }
    
        public virtual User User1 { get; set; }
    }
}
