//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoD
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public string Email { get; set; }
        public string Mdp { get; set; }

        public String ToString()
        {
            return "Email : " + Email + " Mdp : " + Mdp;
        }
    
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
