
package UserAndPayment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserAndPaymentService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserAndPaymentService {


    /**
     * 
     * @param mdp
     * @param email
     */
    @WebMethod(action = "http://tempuri.org/IUserAndPaymentService/addUser")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.AddUserResponse")
    public void addUser(
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "mdp", targetNamespace = "http://tempuri.org/")
        String mdp);

    /**
     * 
     * @param mdp
     * @param email
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "http://tempuri.org/IUserAndPaymentService/isConnectionOK")
    @WebResult(name = "isConnectionOKResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "isConnectionOK", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.IsConnectionOK")
    @ResponseWrapper(localName = "isConnectionOKResponse", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.IsConnectionOKResponse")
    public Boolean isConnectionOK(
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "mdp", targetNamespace = "http://tempuri.org/")
        String mdp);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IUserAndPaymentService/getListUsers")
    @WebResult(name = "getListUsersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getListUsers", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.GetListUsers")
    @ResponseWrapper(localName = "getListUsersResponse", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.GetListUsersResponse")
    public String getListUsers();

    /**
     * 
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IUserAndPaymentService/getMyBills")
    @WebResult(name = "getMyBillsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getMyBills", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.GetMyBills")
    @ResponseWrapper(localName = "getMyBillsResponse", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.GetMyBillsResponse")
    public String getMyBills(
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email);

    /**
     * 
     * @param id
     * @param cb
     * @param email
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "http://tempuri.org/IUserAndPaymentService/addPayment")
    @WebResult(name = "addPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "addPayment", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.AddPayment")
    @ResponseWrapper(localName = "addPaymentResponse", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.AddPaymentResponse")
    public Boolean addPayment(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Long id,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "cb", targetNamespace = "http://tempuri.org/")
        Integer cb);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IUserAndPaymentService/getListPayments")
    @WebResult(name = "getListPaymentsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getListPayments", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.GetListPayments")
    @ResponseWrapper(localName = "getListPaymentsResponse", targetNamespace = "http://tempuri.org/", className = "UserAndPayment.GetListPaymentsResponse")
    public String getListPayments();

}
