
package UserAndPayment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserAndPaymentService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:50828/UserAndPaymentService.svc?wsdl")
public class UserAndPaymentService
    extends Service
{

    private final static URL USERANDPAYMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERANDPAYMENTSERVICE_EXCEPTION;
    private final static QName USERANDPAYMENTSERVICE_QNAME = new QName("http://tempuri.org/", "UserAndPaymentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:50828/UserAndPaymentService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERANDPAYMENTSERVICE_WSDL_LOCATION = url;
        USERANDPAYMENTSERVICE_EXCEPTION = e;
    }

    public UserAndPaymentService() {
        super(__getWsdlLocation(), USERANDPAYMENTSERVICE_QNAME);
    }

    public UserAndPaymentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERANDPAYMENTSERVICE_QNAME, features);
    }

    public UserAndPaymentService(URL wsdlLocation) {
        super(wsdlLocation, USERANDPAYMENTSERVICE_QNAME);
    }

    public UserAndPaymentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERANDPAYMENTSERVICE_QNAME, features);
    }

    public UserAndPaymentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserAndPaymentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IUserAndPaymentService
     */
    @WebEndpoint(name = "BasicHttpBinding_IUserAndPaymentService")
    public IUserAndPaymentService getBasicHttpBindingIUserAndPaymentService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IUserAndPaymentService"), IUserAndPaymentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUserAndPaymentService
     */
    @WebEndpoint(name = "BasicHttpBinding_IUserAndPaymentService")
    public IUserAndPaymentService getBasicHttpBindingIUserAndPaymentService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IUserAndPaymentService"), IUserAndPaymentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERANDPAYMENTSERVICE_EXCEPTION!= null) {
            throw USERANDPAYMENTSERVICE_EXCEPTION;
        }
        return USERANDPAYMENTSERVICE_WSDL_LOCATION;
    }

}
