//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.PaymentServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentServiceReference.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getMyBills", ReplyAction="http://tempuri.org/IPaymentService/getMyBillsResponse")]
        string getMyBills(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getMyBills", ReplyAction="http://tempuri.org/IPaymentService/getMyBillsResponse")]
        System.Threading.Tasks.Task<string> getMyBillsAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/addPayment", ReplyAction="http://tempuri.org/IPaymentService/addPaymentResponse")]
        bool addPayment(long id, string email, int cb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/addPayment", ReplyAction="http://tempuri.org/IPaymentService/addPaymentResponse")]
        System.Threading.Tasks.Task<bool> addPaymentAsync(long id, string email, int cb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getListPayments", ReplyAction="http://tempuri.org/IPaymentService/getListPaymentsResponse")]
        string getListPayments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getListPayments", ReplyAction="http://tempuri.org/IPaymentService/getListPaymentsResponse")]
        System.Threading.Tasks.Task<string> getListPaymentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : UnitTestProject.PaymentServiceReference.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<UnitTestProject.PaymentServiceReference.IPaymentService>, UnitTestProject.PaymentServiceReference.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getMyBills(string email) {
            return base.Channel.getMyBills(email);
        }
        
        public System.Threading.Tasks.Task<string> getMyBillsAsync(string email) {
            return base.Channel.getMyBillsAsync(email);
        }
        
        public bool addPayment(long id, string email, int cb) {
            return base.Channel.addPayment(id, email, cb);
        }
        
        public System.Threading.Tasks.Task<bool> addPaymentAsync(long id, string email, int cb) {
            return base.Channel.addPaymentAsync(id, email, cb);
        }
        
        public string getListPayments() {
            return base.Channel.getListPayments();
        }
        
        public System.Threading.Tasks.Task<string> getListPaymentsAsync() {
            return base.Channel.getListPaymentsAsync();
        }
    }
}
